### ISSUE TITLE
Not works for Windows 11

### ISSUE THREAD

**Issue by frozenade** [RadAd/RadVDDB#1]
It is works up to Windows 10.
Is there any way to make this succeed on Windows 11?

**Comment by RadAd** [comment]
No. Windows 11 does not support DeskBands.

**Comment by frozenade** [comment]
Do you have any solution regarding to this?
I've searched arround the net and found nothing, even on Microsoft's website.

**Comment by RadAd** [comment]
Have you tried Rainmeter, desktop customization tool
<https://www.rainmeter.net/>

Thanks,
Adam.
